print("Enter you first number :")
num1=int(input())
print("Enter you second number :")
num2=int(input())
print("Enter your operation")
print("+Add")
print("-minus")
print("*multiply")
print("/divide")
opr=input()
